# Generated by Django 5.2.3 on 2025-07-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Power', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='data_file',
        ),
        migrations.AddField(
            model_name='scan',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
